### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by tigerza117**
- [x] Test
- [x] Performance
- [x] Implement Jinja2

### CODE REVIEW

**Comment by tigerza117** [comment]
I improve more performance from parallel testing by use ssh cache for reuse session when test another test case

Why?

because i see ssh handshake connection is too long

**Comment by tigerza117** [comment]
Before 37.78s
image


After 9.60s
image

**Comment by tigerza117** [comment]
@SoNicBoom24 Any comment :>

**Review by SoNicBoom24 — APPROVED** [review]
No comment

**Pull request merged**
