### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by tigerza117**
Task
- [ ] Implement jinja2
- [ ] Testing all pass
- [x] Improve performance

### CODE REVIEW

**Comment by tigerza117** [comment]
I improve more performance from parallel testing by use ssh cache for reuse session when test another test case 

Why? 

because i see ssh handshake connection is too long

**Comment by tigerza117** [comment]
Any comment @SoNicBoom24

**Review by SoNicBoom24 — APPROVED** [review]
good job and go to rest

**Comment by tigerza117** [comment]
Before 37.78s

Screenshot 2566-03-01 at 16 46 26

After 9.60s
Screenshot 2566-03-01 at 16 46 54

**Pull request merged**
